export CUDA_VISIBLE_DEVICES=1
export BERT_BASE_DIR=/home/hadoop-aipnlp/cephfs/data/transfer_to_zw03/yangyang113/bert_base
export BERT_MODEL_DIR=/home/hadoop-aipnlp/cephfs/data/bujiahao/outstanding_ckpt/128_model
#export BERT_MODEL_DIR=./lcqmc_mt_cut_l6h384i1200
export MY_DATASET=./train_data/ #全局变量 数据集所在地址
export OUTPUT=./output/lcqmc_cut_l6h384i1200/
python run_classifier_cut.py \
  --task_name=lcqmc \
  --do_train=true \
  --do_eval=true \
  --do_predict=true \
  --data_dir=$MY_DATASET \
  --vocab_file=$BERT_BASE_DIR/vocab.txt \
  --bert_config_file=$BERT_BASE_DIR/bert_config_6_384.json \
  --init_checkpoint=$BERT_MODEL_DIR/model.ckpt-666600 \
  --max_seq_length=128 \
  --train_batch_size=32 \
  --predict_batch_size=128 \
  --learning_rate=5e-5 \
  --num_train_epochs=3.0 \
  --output_dir=$OUTPUT \
