export CUDA_VISIBLE_DEVICES=0
export BERT_BASE_DIR=/home/hadoop-aipnlp/cephfs/data/transfer_to_zw03/yangyang113/bert_base
#export BERT_MODEL_DIR=/home/hadoop-aipnlp/cephfs/data/bujiahao/outstanding_ckpt/128_model
#export BERT_MODEL_DIR=/home/hadoop-aipnlp/cephfs/data/transfer_to_zw03/yangyang113/bert_base/train_log/student_3_384_comment_initfromcommon
export BERT_MODEL_DIR=./output/lcqmc_siamese_l3h384i1200_b192_addmax_alltoken
export MY_DATASET=./train_data/test #全局变量 数据集所在地址
export OUTPUT=./output/lcqmc_siamese_l3h384i1200_b192_addmax_alltoken/
python run_classifier_siamese_embedding.py \
  --task_name=lcqmc \
  --pooling_strategy=mean \
  --do_train=false \
  --do_eval=false \
  --do_predict=true \
  --data_dir=$MY_DATASET \
  --vocab_file=$BERT_BASE_DIR/vocab.txt \
  --bert_config_file=$BERT_BASE_DIR/bert_config_6_128_A2.json \
  --init_checkpoint=$BERT_MODEL_DIR/model.ckpt-471000 \
  --max_seq_length=64 \
  --train_batch_size=192 \
  --predict_batch_size=1 \
  --learning_rate=2e-5 \
  --num_train_epochs=8.0 \
  --output_dir=$OUTPUT
