export CUDA_VISIBLE_DEVICES=0
export BERT_BASE_DIR=/home/hadoop-aipnlp/cephfs/data/transfer_to_zw03/yangyang113/bert_base
#export BERT_MODEL_DIR=/home/hadoop-aipnlp/cephfs/data/bujiahao/outstanding_ckpt/128_model
#export BERT_MODEL_DIR=/home/hadoop-aipnlp/cephfs/data/transfer_to_zw03/yangyang113/bert_base/train_log/bert_distil_minilm_L6h128I512A2_common128_wa
#export BERT_MODEL_DIR=/home/hadoop-aipnlp/cephfs/data/transfer_to_zw03/yangyang113/finetune/LCQMC/output/quanwen_embedding/ckpte1.8
#export BERT_MODEL_DIR=/home/hadoop-aipnlp/cephfs/data/transfer_to_zw03/yangyang113/finetune/LCQMC/output/quanwen_embedding_cosine/ckpte1.5
#export BERT_MODEL_DIR=/home/hadoop-aipnlp/cephfs/data/transfer_to_zw03/yangyang113/finetune/LCQMC/output/quanwen_embedding_cosine/model.ckpt-218500
#export BERT_MODEL_DIR=./output/quanwen_pairwise_embedding/model.ckpt-260
#export BERT_MODEL_DIR=./output/quanwen_pairwise_embedding1/model.ckpt-340305
export BERT_MODEL_DIR=./output/quanwen_pairwise_embedding_v2/model.ckpt-125434
#export BERT_MODEL_DIR=./output/search_siamese_l6h128A2_b192_addmax_alltoken
export MY_DATASET=./train_data/quanwen #全局变量 数据集所在地址
#export OUTPUT=./output/search_spuall_3/
#export OUTPUT=./output/quanwen_embedding_cosine
#export OUTPUT=./output/quanwen_pairwise_embedding
export OUTPUT=./output/quanwen_pairwise_embedding_v2
#export OUTPUT=/home/hadoop-aipnlp/cephfs/data/transfer_to_zw03/yangyang113/finetune/LCQMC/output/quanwen_embedding_cosine/ckpte1.5
#export OUTPUT=/home/hadoop-aipnlp/cephfs/data/transfer_to_zw03/yangyang113/finetune/LCQMC/output/quanwen_embedding/ckpte1.8
python s_bert_ab_test.py \
  --task_name=lcqmc \
  --pooling_strategy=mean \
  --do_train=false \
  --do_eval=true \
  --do_predict=false \
  --data_dir=$MY_DATASET \
  --test_flie_name=test.tsv \
  --vocab_file=$BERT_BASE_DIR/vocab.txt \
  --bert_config_file=$BERT_BASE_DIR/bert_config_6_128_A2.json \
  --init_checkpoint=$BERT_MODEL_DIR \
  --max_seq_length_a=18 \
  --max_seq_length_b=64 \
  --train_batch_size=192 \
  --learning_rate=2e-5 \
  --num_train_epochs=5.0 \
  --do_save=false \
  --output_dir=$OUTPUT
